FROM chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:3.0.20287-769529fa4

MAINTAINER Mingxun Wang "mwang87@gmail.com"

RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential

RUN pip3 install ftputil
RUN pip3 install flask
RUN pip3 install gunicorn
RUN pip3 install requests
RUN pip3 install celery
RUN pip3 install joblib
RUN pip3 install redis
RUN apt-get install -y zip unzip

COPY . /app
WORKDIR /app
