version: '3'
services:
  gnpsquickstart-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: quickstart.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: quickstart.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net